name: voli
description: A command-line app that adds boilerplate code to your flutter app!
version: 1.0.0-dev.3
homepage: https://github.com/meta-boy/voli

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  yaml: ^2.2.0
  path: ^1.7.0
  args: ^1.6.0
  http: ^0.12.0+4
  io: ^0.3.4
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  import_sorter: ^1.0.2
